# Generated by Django 3.2.6 on 2021-08-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('modified', models.DateField(auto_now_add=True)),
                ('column_separator', models.CharField(choices=[('', '-------'), (',', 'Comma(,)'), ('.', 'Dot(.)'), ('|', 'Stick(|)')], default=',', max_length=32)),
                ('string_separator', models.CharField(choices=[('', '-------'), ('"', 'Double-quote(")'), ("'", "Quote(')"), (';', 'Semicolon(;)')], default=';', max_length=32)),
                ('user_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv-files')),
                ('task_id', models.CharField(blank=True, max_length=124, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='main.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('type', models.CharField(choices=[('', '-------'), ('FN', 'Full name'), ('E', 'Email'), ('DN', 'Domain name'), ('CN', 'Company name'), ('I', 'Integer'), ('D', 'Date')], max_length=32)),
                ('order', models.PositiveSmallIntegerField()),
                ('range_from', models.PositiveIntegerField(blank=True, null=True)),
                ('range_to', models.PositiveIntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.schema')),
            ],
        ),
    ]
